---
- name: install the latest version of docker
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: Install Docker
    ansible.builtin.shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh 
  - name: create docker group
    shell: sudo usermod -aG docker ${USER} && newgrp docker